name: Documentation Issue
description: Report an issue with documentation or suggest improvements
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Clear and accurate docs benefit everyone.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this hasn't been reported
          required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation is this about?
      options:
        - README
        - API Documentation / Code Comments
        - Contributing Guidelines
        - Code of Conduct
        - Security Policy
        - Installation Instructions
        - Usage Examples
        - Architecture / Design Docs
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect / Outdated information
        - Unclear / Confusing explanation
        - Broken link
        - Typo / Grammar / Formatting
        - Enhancement / Improvement suggestion
        - Translation issue
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Document Location
      description: Where is the documentation issue located?
      placeholder: |
        File: README.md
        Section: "Getting Started"
        Link: https://...
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: Describe the documentation issue
      placeholder: Describe what's wrong or missing...
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: If applicable, quote or describe the current documentation
      placeholder: |
        Current text:
        "..."
      render: markdown

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: |
        Suggested text:
        "..."
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, examples, or references
      placeholder: Add any other context, screenshots, links to good examples, etc...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to submit a PR with the documentation fix?
      options:
        - label: I am willing to submit a PR for this documentation change
