global using Xunit;
global using FluentAssertions;
global using FluentValidation;
global using Bogus;
global using FinSkew.Ui.Models.ViewModels.InputModels;
global using FinSkew.Ui.Models.ViewModels.ResultModels;
global using FinSkew.Ui.Services.Implementations;
global using FinSkew.Ui.Services.Validators.InputModels;
global using FinSkew.Ui.UnitTests.TestHelpers;