name: finskew-deploy-template

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string
      runProvisioning:
        type: boolean
        required: true
        default: false

env:
  APP_NAME: finskew
  DOTNET_VERSION_10: "10.0.x"
  FINSKEW_PUBLISH_CONFIGURATION: ReleaseAot
  RESOURCE_GROUP_NAME: finskew-rg
  RESOURCE_LOCK_NAME: finskew-rg-delete-lock
  # metadata will be stored, and not where the resource groups will be deployed.
  # You can specify any location for `SUB_DEPLOYMENT_REGION`. It's the region where 
  # the deployment metadata will be stored, and not where the resource groups will be deployed.
  SUB_DEPLOYMENT_REGION: centralindia

jobs:
  provision:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environmentName }}
    timeout-minutes: 30
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
      - name: azure login
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.SERVICEPRINCIPAL }}
      # temporarily use az cli to upgrade bicep
      # Context: https://github.com/Azure/bicep/issues/16681#issuecomment-2747568200
      - name: upgrade bicep
        uses: azure/CLI@v2.2.0
        with:
          inlineScript: az bicep upgrade
      #
      # section #1: provisioning the resources on Azure using bicep templates
      #
      # The first step is to create the resource group: `finskew-rg`.
      # The below step can also be manually executed as follows:
      # az deployment sub create --location {LOCATION} --template-file .\createResourceGroup.bicep
      # Note: You can specify any location for `{LOCATION}`. It's the region where the deployment metadata will be stored, and not
      # where the resource groups will be deployed.
      # @TODO: The 'azure/arm-deploy' action will soon be deprecated. Move to the 'azure/bicep-deploy' github action.
      - name: create resource group
        uses: Azure/arm-deploy@v2
        if: ${{ inputs.runProvisioning == true }}
        with:
          scope: subscription
          region: ${{ env.SUB_DEPLOYMENT_REGION }}
          template: ./infra/createResourceGroup.bicep
          parameters: rgName=${{ env.RESOURCE_GROUP_NAME }} envName=${{ inputs.environmentName }} githubCommitSha=${{ github.sha }} githubWorkflowRunId=${{ github.run_id }} githubRef=${{ github.ref }}
      # Delete resource lock if it exists on the resource group
      - name: delete any existing resource lock
        uses: azure/CLI@v2.2.0
        if: ${{ inputs.runProvisioning == true }}
        with:
          inlineScript: |
            az lock delete --name ${{ env.RESOURCE_LOCK_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }} || echo "No existing lock to delete"
      # Add resource lock
      - name: add resource lock
        uses: azure/CLI@v2.2.0
        if: ${{ inputs.runProvisioning == true }}
        with:
          inlineScript: az lock create --name ${{ env.RESOURCE_LOCK_NAME }} --lock-type CanNotDelete --resource-group ${{ env.RESOURCE_GROUP_NAME }}

  build-deploy-finskew-app:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environmentName }}
    timeout-minutes: 10
    needs: provision
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
      - name: setup dotnet
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION_10 }}
      - name: dotnet restore
        run: dotnet restore
        working-directory: ./src/FinSkew.Ui
      - name: install wasm tools workload
        run: dotnet workload install wasm-tools --skip-manifest-update
      - name: run unit tests
        run: dotnet test ./tests/FinSkew.Ui.UnitTests/FinSkew.Ui.UnitTests.csproj --logger trx --results-directory ./tests/FinSkew.Ui.UnitTests/TestResults-${{ github.run_id }}-${{ github.run_attempt }}
      - name: publish unit test results
        uses: actions/upload-artifact@v4.3.1
        with:
          name: FinSkew.Ui.UnitTests
          path: ./tests/FinSkew.Ui.UnitTests/TestResults-${{ github.run_id }}-${{ github.run_attempt }}
      - name: build finskew ui
        run: dotnet publish ./src/FinSkew.Ui/FinSkew.Ui.csproj -c ${{ env.FINSKEW_PUBLISH_CONFIGURATION }} -o ./Publish/FinSkew.Ui
      - name: azure login
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.SERVICEPRINCIPAL }}
      - name: get swa deployment token
        id: get-swaDeploymentToken
        uses: azure/CLI@v2.2.0
        with:
          inlineScript: echo "swaDeploymentToken"="$(az staticwebapp secrets list -g ${{ env.RESOURCE_GROUP_NAME }} -n ${{ env.APP_NAME }} --query properties.apiKey -o tsv)" >> $GITHUB_OUTPUT
      - name: deploy finskew ui to swa
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.get-swaDeploymentToken.outputs.swaDeploymentToken }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./Publish/FinSkew.Ui/wwwroot"
          api_location: "" # No API in this app
          output_location: "" # No build step, so output location is same as app location
